#!/bin/bash

# Script to backup a Minetest server.  Note that this script simply creates a
# single backup and overwrites it on each use.  Another program must be used to
# store and rotate said backup for posterity.

# Print a usage message with an optional error message and exit the program.
SERVICE_DEFAULT="minetest-server"
HOMEDIR_DEFAULT="/var/lib/minetest"
usage_print() {
	if [ $# -gt 0 ]; then
		echo "ERROR: $1."
		echo ""
	fi
	echo "USAGE: $0 [SERVICE] [HOMEDIR]"
	echo -e "\tSERVICE: Service name according to OpenRC (default: '${SERVICE_DEFAULT}')"
	echo -e "\tHOMEDIR: Home directory of Minetest user (default: '${HOMEDIR_DEFAULT}')"
	if [ $# -gt 0 ]; then
		exit 1
	fi
	exit 0
}

# Parse arguments.
if [ $# -gt 2 ]; then
	usage_print "Too many arguments"
elif [ $# -gt 0 ]; then
	if [ "$1" == "-h" -o "$1" == "--help" ]; then
		usage_print
	fi
fi
SERVICE=${1:-"${SERVICE_DEFAULT}"}
HOMEDIR=${2:-"${HOMEDIR_DEFAULT}"}

# Validate arguments.
if [ ! -f "/etc/init.d/${SERVICE}" ]; then
	usage_print "No such service '${SERVICE}'"
elif [ ! -d "${HOMEDIR}/.minetest" ]; then
	usage_print "Could not find Minetest directory at '${HOMEDIR}/.minetest'"
fi

# Prepare to execute.
echo "Backing up Minetest service '${SERVICE}' with home directory '${HOMEDIR}'"
set -ex

# Clean existing backup.
rm -rf "${HOMEDIR}"/backup.tar{,.bz2}

# Stop the server.
rc-service ${SERVICE} stop

# Create the backup.
tar -cvf "${HOMEDIR}/backup.tar" "${HOMEDIR}/.minetest"

# Restart the server.
rc-service ${SERVICE} start

# Compress the backup.
bzip2 "${HOMEDIR}/backup.tar"
chown mtbackup:mtbackup "${HOMEDIR}/backup.tar.bz2"
